language: python
sudo: false

python:
  - 3.5

before_install:
    - apt-get -qq update
    - apt-get install -y pandoc enchant

install:
  - pip install -r requirements-dev.txt

script:
  - invoke check_notebooks
